version: 2
updates:
  # Enable npm updates for root package.json
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "diegocortes3211-design"
    labels:
      - "dependencies"
      - "security"
    commit-message:
      prefix: "chore"
      include: "scope"

  # Enable npm updates for client package.json  
  - package-ecosystem: "npm"
    directory: "/client"
    schedule:
      interval: "weekly" 
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "diegocortes3211-design"
    labels:
      - "dependencies"
      - "security"
    commit-message:
      prefix: "chore"
      include: "scope"

  # Enable updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 3
    reviewers:
      - "diegocortes3211-design"
    labels:
      - "ci/cd"
      - "dependencies"
    commit-message:
      prefix: "ci"
      include: "scope"