site_name: Xikizpedia — DreamAware.ai
site_url: https://diegocortes3211-design.github.io/dreamaware.cc
theme:
  name: material
  features:
    - navigation.instant
    - navigation.sections
    - search.suggest
    - content.code.copy
  palette:
    - scheme: slate
nav:
  - Home: index.md
  - Portfolio:
    - Architecture: portfolio/architecture.md
    - Security Program: portfolio/security.md
    - Supply Chain: supply-chain.md
  - Research:
    - AI / Agents: research/agents.md
    - Blockchain (VoidCoin): research/voidcoin.md
  - Links & Citations:
    - Canonical Links: links.md
    - References: references.md
plugins:
  - search
  - bibtex:
      bib_file: docs/references.bib
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - attr_list
  - footnotes
