# k8s/video-gen/llm-service.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: llm-service
  namespace: video-gen
  annotations:
    # Vault integration via Kubernetes auth
    vault.hashicorp.com/role: "video-gen-llm"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-service
  namespace: video-gen
spec:
  replicas: 3
  selector:
    matchLabels:
      app: llm-service
      version: v1
  template:
    metadata:
      labels:
        app: llm-service
        version: v1
      annotations:
        # Vault agent injection
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "video-gen-llm"
        vault.hashicorp.com/agent-inject-secret-llm-keys: "video-gen/llm/credentials"
        # SPIFFE workload attestation
        spiffe.io/workload-name: "llm-service"
    spec:
      serviceAccountName: llm-service
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        fsGroup: 65534
      containers:
      - name: llm
        image: dreamaware/video-gen-llm:latest
        imagePullPolicy: Always
        ports:
        - name: grpc
          containerPort: 8081
        - name: metrics
          containerPort: 9090
        env:
        - name: SERVICE_NAME
          value: "llm-service"
        - name: VAULT_ADDR
          value: "http://vault.vault.svc.cluster.local:8200"
        - name: SPIRE_SOCKET
          value: "/run/spire/sockets/agent.sock"
        - name: CRDB_DSN
          valueFrom:
            secretKeyRef:
              name: crdb-credentials
              key: dsn
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop: ["ALL"]
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: spire-agent-socket
          mountPath: /run/spire/sockets
          readOnly: true
        livenessProbe:
          grpc:
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          grpc:
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: tmp
        emptyDir: {}
      - name: spire-agent-socket
        hostPath:
          path: /run/spire/sockets
          type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: llm-service
  namespace: video-gen
spec:
  selector:
    app: llm-service
  ports:
  - name: grpc
    port: 8081
    targetPort: 8081
  - name: metrics
    port: 9090
    targetPort: 9090
---
# Istio PeerAuthentication for strict mTLS
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: llm-service-mtls
  namespace: video-gen
spec:
  selector:
    matchLabels:
      app: llm-service
  mtls:
    mode: STRICT
---
# AuthorizationPolicy: only allow calls from orchestrator
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: llm-service-authz
  namespace: video-gen
spec:
  selector:
    matchLabels:
      app: llm-service
  action: ALLOW
  rules:
  - from:
    - source:
        principals:
        - "cluster.local/ns/video-gen/sa/orchestrator"
        - "cluster.local/ns/video-gen/sa/llm-service"  # Self for health checks