name: Add Link to Memory
description: Append a canonical link to memory/links.yml
labels: [link]
body:
  - type: input
    id: name
    attributes: { label: Display Name, placeholder: "e.g., My Blog Post" }
    validations: { required: true }
  - type: input
    id: url
    attributes: { label: URL, placeholder: "https://…" }
    validations: { required: true }
  - type: input
    id: tags
    attributes: { label: Tags (comma-separated), placeholder: "research,ai,security" }
