default:
  provider: openai
  model: gpt-4o-mini
providers:
  openai:
    env: OPENAI_API_KEY
    models: [gpt-4o, gpt-4o-mini]
  anthropic:
    env: ANTHROPIC_API_KEY
    models: [claude-3-5-sonnet, claude-3-5-haiku]
  gemini:
    env: GOOGLE_API_KEY
    models: [gemini-2.0-flash, gemini-1.5-pro]
  grok:
    env: XAI_API_KEY
    models: [grok-2, grok-2-mini]