default:
  provider: gemini
  model: gemini-1.5-pro
routes:
  short_json:
    provider: openai
    model: gpt-4o-mini
  long_doc:
    provider: gemini
    model: gemini-1.5-pro
  code:
    provider: anthropic
    model: claude-3-5-sonnet-20240620

providers:
  openai:
    env: OPENAI_API_KEY
    models: [gpt-4o, gpt-4o-mini, gpt-5-thinking]
  anthropic:
    env: ANTHROPIC_API_KEY
    models: [claude-3-5-sonnet, claude-3-5-haiku]
  gemini:
    env: GOOGLE_API_KEY
    models: [gemini-2.0-flash, gemini-1.5-pro, gemini-2.5-flash]
  grok:
    env: XAI_API_KEY
    models: [grok-2, grok-2-mini]
  deepthink:
    env: DEEPTHINK_API_KEY
    models: [deepthink-pro]