name: Agents Governance Gate
on:
  pull_request:
    paths:
      - 'agents/prompts/**'
      - 'agents/workflows/**'
permissions:
  contents: read
  pull-requests: write
jobs:
  require-human:
    runs-on: ubuntu-latest
    steps:
      - name: Disallow bot-initiated merge
        uses: actions-ecosystem/action-regex-match@v2
        id: bot
        with:
          text: ${{ github.actor }}
          regex: 'bot'
      - name: Block if bot
        if: steps.bot.outputs.match != ''
        run: |
          echo "Agent/self/bot merges are disallowed." >&2
          exit 1
      - name: Require codeowners approval
        uses: blendle/auto-approve-action@v2
        if: ${{ always() }}
        with:
          review-message: "Governance check: Human approval required."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}