name: Deploy Web (OIDC)

on:
  push:
    branches: [ "main" ]
    paths: [ "web/**" ]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

env:
  AWS_REGION: us-east-1
  BUCKET: your-artifacts-bucket
  CF_DISTRIBUTION_ID: E123ABC456

jobs:
  deploy:
    environment: prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Build
        run: |
          npm ci --prefix web
          npm run build --prefix web

      - name: Upload to S3
        run: |
          aws s3 sync web/dist "s3://${BUCKET}/web/" --delete

      - name: Invalidate CloudFront
        if: env.CF_DISTRIBUTION_ID != ''
        run: |
          aws cloudfront create-invalidation \
            --distribution-id "${CF_DISTRIBUTION_ID}" \
            --paths "/*"
