name: Deploy Xikizpedia API

on:
  push:
    branches: [ main ]
    paths:
      - 'services/xikizpedia_api/**'

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r services/xikizpedia_api/requirements.txt

      - name: Lint with ruff
        run: |
          pip install ruff
          ruff check services/xikizpedia_api/

      - name: Run placeholder deployment
        run: |
          echo "✅ Deployment successful (placeholder)"
          echo "In a real environment, this step would deploy the service."
          echo "For example, using a command like 'vercel deploy --prod' or similar."