name: Slack UCAPI Bridge and Cursor Adapter CI

on:
  push:
    branches: [ main ]
    paths:
      - 'services/slack/**'
      - 'services/llm_adapters/**'
      - 'tests/test_ucapi_stub.py'
      - 'tests/test_cursor_adapter.py'
      - '.github/workflows/slack-ucapi.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'services/slack/**'
      - 'services/llm_adapters/**'
      - 'tests/test_ucapi_stub.py'
      - 'tests/test_cursor_adapter.py'
      - '.github/workflows/slack-ucapi.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[slack,dev]"

      - name: Run tests
        run: |
          pytest tests/test_ucapi_stub.py tests/test_cursor_adapter.py
        env:
          # Set dummy env vars for import-time checks
          SLACK_BOT_TOKEN: "dummy"
          SLACK_SIGNING_SECRET: "dummy"
          UCAPI_URL: "http://dummy.url"
          UCAPI_SERVICE_KEY: "dummy"
          CURSOR_API_KEY: "dummy"