name: Slack Bridge and UCAPI CI

on:
  push:
    branches: [ main ]
    paths:
      - 'services/slack/**'
      - 'services/llm_adapters/cursor_pro.py'
      - 'tests/test_slack_bridge.py'
      - 'tests/test_cursor_adapter.py'
      - '.github/workflows/slack-ucapi.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'services/slack/**'
      - 'services/llm_adapters/cursor_pro.py'
      - 'tests/test_slack_bridge.py'
      - 'tests/test_cursor_adapter.py'
      - '.github/workflows/slack-ucapi.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest tests/test_slack_bridge.py tests/test_cursor_adapter.py