name: Unit tests
on:
  pull_request:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  python-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install test deps
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov
      - name: Run pytest with coverage
        run: |
          pytest -q --maxfail=1 --junitxml=pytest-report.xml --cov=. --cov-report=xml
      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: pytest-report
          path: pytest-report.xml
      - name: Upload coverage xml
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml

  publish-badge:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: python-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Retrieve coverage xml
        uses: actions/download-artifact@v4
        with:
          name: coverage-xml
          path: .
      - name: Render coverage badge
        run: python scripts/coverage_badge.py
      - name: Commit badge
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add assets/badges/coverage.svg
          git commit -m "chore(ci): update coverage badge [skip ci]" || echo "no changes"
          git push